name: Baikal
version: "0.11.1"
description: Lightweight CalDAV+CardDAV server
slug: baikal

# tot aan de echte locatie
url: https://github.com/Moozzuzz/HA-addons
arch: 
  - aarch64
  - amd64

map:
  - config:rw
  - ssl:rw
  - addons:rw
  - share:rw
 
devices: 
  /dev/net/tun

startup: services
init: false
boot: auto
backup: cold

host_network: "true"
ports: 
  80/tcp: 8013
ports_description:
  80/tcp: Web UI port
ingress: "true"
ingress_port: "8013"
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
panel_icon: mdi:calendar-account
panel_title: Baikal

#user config
options:
  env_vars: []

schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?

slug: baikal
udev: true
