name: miniDLNA,
version: "0.1"
description: miniDLNA
slug: minidlna

# tot aan de echte locatie
url: https://github.com/Moozzuzz/HA-addons
arch: 
  - aarch64
  - amd64
ports: 
  1900/udp: 1900

map:
  - config:rw
  - ssl:rw
  - addons:rw
  - share:rw
  - backup:rw
  - media:rw

privileged: 
  NET_ADMIN

devices: 
  /dev/net/tun

host_network: "true"

startup: services
init: false
boot: auto
backup: cold

ingress: "true"
ingress_port: "9998"
webui: http://[HOST]:[PORT:9998]
panel_icon: mdi:dlna
panel_title: miniDLNA

#user config
options:
  media_dir: /media;/share
  options: -d

schema: 
  media_dir: str
  options: str
